FROM candleends/ros2dev:latest

RUN apt-get update && apt-get install -y \
    python2.7 \
    cmake \
    default-jre \
  && rm -rf /var/lib/apt/lists/*


RUN git clone https://github.com/emscripten-core/emsdk.git ~/emsdk
RUN (cd ~/emsdk && ./emsdk install latest)
RUN (cd ~/emsdk && ./emsdk activate latest)
RUN echo "source ~/emsdk/emsdk_env.sh" >> ~/.bashrc
# TODO(emersonknapp) is there a better way around this?
RUN sed -i 's/^set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE/# set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE/' \
  ~/emsdk/fastcomp/emscripten/cmake/Modules/Platform/Emscripten.cmake
